
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 cake_red.glb --transform --types
-->




    <script lang="ts">

				
	
import type * as THREE from 'three'
        import { Group } from 'three'
        import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        type $$Props = Props<THREE.Group>
        type $$Events = Events<THREE.Group>
        type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

        export const ref = new Group()

				

        type GLTFResult = {
    nodes: {
      Whole_Cheesecake_0: THREE.Mesh
      
    }
    materials: {
      Cheesecake: THREE.MeshBasicMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/cake_red-transformed.glb', {"useDraco":true})
    

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T.Group scale={0.01} >
<T.Mesh geometry={gltf.nodes.Whole_Cheesecake_0.geometry} material={gltf.materials.Cheesecake} position={[86, 0, 99,]} />

</T.Group>

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	