
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ybot.glb --transform
-->




    <script>

				
	
        import { Group } from 'three'
        import { T, forwardEventHandlers } from '@threlte/core'
        import { useGltf, useGltfAnimations } from '@threlte/extras'
	

        
        
        

        export const ref = new Group()

				

        

        const gltf = useGltf('/ybot-transformed.glb', {"useDraco":true})
    export const { actions, mixer } = useGltfAnimations(gltf, ref)

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T.Group name="Scene" >
<T.Group name="Armature" rotation={[Math.PI / 2, 0, 0,]} scale={0.01} >
<T is={gltf.nodes.mixamorigHips} />
<T.SkinnedMesh name="Alpha_Joints" geometry={gltf.nodes.Alpha_Joints.geometry} material={gltf.materials['Alpha_Joints_MAT.001']} skeleton={gltf.nodes.Alpha_Joints.skeleton} />
<T.SkinnedMesh name="Alpha_Surface" geometry={gltf.nodes.Alpha_Surface.geometry} material={gltf.materials['Alpha_Body_MAT.001']} skeleton={gltf.nodes.Alpha_Surface.skeleton} />

</T.Group>

</T.Group>

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	